/* A bedtime alarm your phone will fire whether or not this app is open.
 *
 * The honest limit of everything else in here is that a static web app cannot
 * reach you when it is closed — and being closed is the failure mode. You are
 * not late because the app failed to persuade you; you are late because you
 * never opened it and went to a feed instead. Web Push would fix that and needs
 * a server, which would end the no-accounts, no-server promise this whole
 * project is built on.
 *
 * A calendar event does it with no server at all. You add it once; the phone
 * fires it every night, offline, forever, from a closed screen — and it keeps
 * firing if this app is deleted, which is either a bug or the most honest
 * feature in the project depending on your mood.
 *
 * RFC 5545. Deliberately minimal: one VEVENT, one daily RRULE, two VALARMs. No
 * library, no network, and small enough to read in full before trusting it with
 * your sleep.
 */

import { parseClock, formatClockLabel } from './time.js';
import { pad2 } from './util.js';

/** How long before bedtime the first warning fires. */
export const ALARM_LEAD_MINUTES = 30;

/**
 * Folded to 75 octets as the spec requires, splitting on characters rather than
 * bytes — every string here is generated by this app and stays inside ASCII, so
 * the two are the same and the simpler rule is the safe one.
 */
function fold(line) {
  if (line.length <= 75) return line;
  const parts = [line.slice(0, 75)];
  let rest = line.slice(75);
  while (rest.length > 74) {
    parts.push(` ${rest.slice(0, 74)}`);
    rest = rest.slice(74);
  }
  if (rest) parts.push(` ${rest}`);
  return parts.join('\r\n');
}

/** Commas, semicolons, backslashes and newlines are structure in this format. */
function esc(text) {
  return String(text)
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\n/g, '\\n');
}

const stamp = (d) => `${d.getUTCFullYear()}${pad2(d.getUTCMonth() + 1)}${pad2(d.getUTCDate())}`
  + `T${pad2(d.getUTCHours())}${pad2(d.getUTCMinutes())}${pad2(d.getUTCSeconds())}Z`;

/**
 * A nightly bedtime alarm as an .ics file.
 *
 * Floating local time — no TZID and no Z on DTSTART — so it fires at the same
 * wall clock wherever the phone is. A bedtime is 11:30pm where you are standing;
 * pinning it to a zone would move it when you travel, which is the one time you
 * least want your alarm to wander.
 */
export function bedtimeAlarmIcs(bedtime, { now = new Date(), lead = ALARM_LEAD_MINUTES } = {}) {
  const parsed = parseClock(bedtime);
  if (!parsed) return null;

  // The first occurrence is today if the time is still ahead, otherwise
  // tomorrow — so adding the file never starts with a missed alarm.
  const start = new Date(now.getFullYear(), now.getMonth(), now.getDate(), parsed.hours, parsed.minutes, 0, 0);
  if (start.getTime() <= now.getTime()) start.setDate(start.getDate() + 1);
  const local = (d) => `${d.getFullYear()}${pad2(d.getMonth() + 1)}${pad2(d.getDate())}`
    + `T${pad2(d.getHours())}${pad2(d.getMinutes())}00`;

  const label = formatClockLabel(bedtime);
  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//NightCheck//Bedtime//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    // Stable, so re-adding the file after changing your bedtime REPLACES the
    // old event rather than leaving you with two alarms disagreeing about when
    // to sleep. Derived from the time itself, which is the only thing that
    // distinguishes one of these from another.
    `UID:nightcheck-bedtime-${parsed.hours}-${parsed.minutes}@nightcheck.local`,
    `DTSTAMP:${stamp(now)}`,
    `DTSTART:${local(start)}`,
    'DURATION:PT1M',
    'RRULE:FREQ=DAILY',
    `SUMMARY:${esc('Bedtime')}`,
    `DESCRIPTION:${esc(`Your NightCheck target is ${label}. Put the phone down.`)}`,
    'TRANSP:TRANSPARENT',
    // Two alarms, and the earlier one is the one that matters. Being told at
    // bedtime that it is bedtime is a notification about a decision you have
    // already made; being told half an hour out is the only moment where the
    // information can still change what happens.
    'BEGIN:VALARM',
    'ACTION:DISPLAY',
    `TRIGGER:-PT${Math.max(0, Math.round(lead))}M`,
    `DESCRIPTION:${esc(`${Math.max(0, Math.round(lead))} minutes to ${label}. Start winding down.`)}`,
    'END:VALARM',
    'BEGIN:VALARM',
    'ACTION:DISPLAY',
    'TRIGGER:PT0M',
    `DESCRIPTION:${esc(`${label}. Lights out.`)}`,
    'END:VALARM',
    'END:VEVENT',
    'END:VCALENDAR',
  ];
  // CRLF throughout, which the spec requires and which some calendar importers
  // genuinely refuse the file over.
  return `${lines.map(fold).join('\r\n')}\r\n`;
}
